services:
  app:
    build: .
    container_name: ComputerStatus
    ports:
      - "${COMPUTERSTATUS_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json:z
